syntax = "proto3";

package user;

option java_package = "com.moimmee.proto.user";
option java_outer_classname = "UserServiceProto";

import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";

// 요청/응답 메시지

service UserService {
  rpc Register(RegisterUserRequest) returns (google.protobuf.Empty);
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc GetAllUsers(google.protobuf.Empty) returns (GetAllUsersResponse);
}

message RegisterUserRequest {
  string name = 1;
  string gender = 2;
  string email = 3;
}

message GetUserRequest {
  int64 id = 1;
}

message GetUserResponse {
  string name = 1;
  string role = 2;
  string gender = 3;
  string email = 4;
}

message GetAllUsersResponse {
  repeated GetUserResponse user = 1;
}