server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

grpc:
  server:
    port: 6565

---
spring:
  config:
    activate:
      on-profile: k8s

logging:
  level:
    root: INFO
    com.moimmee: DEBUG